-- 在第一行，优先加载
require("plugins.plugins")

require("core.opt")
require("core.keymaps")

-- 启用插件
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.mason").config()
require("plugins.mason-lsp").config()
require("plugins.lsp").config()
require("plugins.gopher").config()
require("plugins.cmp")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.markdown")
require("plugins.git")
require("plugins.dashboard")
require("plugins.nvim-lastplace").config()
require("plugins.hop").config()
