return {
  {
    "williamboman/mason.nvim",
    event = "VeryLazy",
    opts = {
      ui = {
        border = "rounded",
      },
      ensure_installed = {
        "debugpy",
        "delve",
        "gofumpt",
        "goimports",
        "gopls",
        "java-debug-adapter",
        "java-test",
        "jdtls",
        "js-debug-adapter",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "pyright",
        "ruff-lsp",
        "shfmt",
        "sqlfluff",
        "stylua",
        "taplo",
        "vtsls",
        "vue-language-server",
        "yaml-language-server",
        "rust-analyzer",
      },
    },
  },
}
